//! ZPAQ pre-processor wrappers — port of `LZBuffer` from
//! `plugins/zpaq/upstream/libzpaq.cpp:6473`.
//!
//! These transform raw input into the byte stream that the matching
//! PCOMP postprocessor (generated by `makeConfig`) decodes back to
//! the original. Three modes are documented upstream:
//!
//!   * **Level 1** — variable-length LZ77 with Elias-gamma length
//!     coding. NOT YET PORTED — the bit-level packing is non-trivial
//!     and most archives can be represented in level 2 or 3 anyway.
//!   * **Level 2** — byte-aligned LZ77. Match codes are packed as
//!     `[01..11]xxxxxx off[2..4]` and literals as `00xxxxxx data[x+1]`.
//!     Matching is done with a small `(1 << args[5])`-bucket hash
//!     table over `in[i+3]` low bits.
//!   * **Level 3** — Burrows-Wheeler transform. Output is
//!     `in[n-1] | bwt[0..n] (with sa==0 ⇒ 0xFF) | idx_LE_4`.
//!     The suffix array comes from [`bsc_rs::sais::sais_u8`].
//!
//! Calling convention for `LzArgs` mirrors upstream's `args[0..6]`.

#![allow(dead_code)]

#[derive(Debug, Clone, Copy)]
pub struct LzArgs {
    /// Log2 of buffer size in MiB. Affects max input length and the
    /// `rb` bit count for variable-LZ77 (level 1, unused here).
    pub log_block_mib: u32,
    /// Level + E8E9 flag: `(level&3) ∈ {1,2,3}`, top bit (4) → E8E9.
    /// Level 0 (no preprocessing) is handled by `Compresser` directly,
    /// not by this module.
    pub level_flag: u32,
    /// LZ77 minimum match length (`args[2]`). Must be ≥1 for level 2.
    pub min_match: u32,
    /// Optional secondary minimum match length / context order
    /// (`args[3]`). 0 disables. Not currently used by this port.
    pub min_match2: u32,
    /// Log2 of search bucket size — `bucket = (1 << args[4]) - 1`
    /// matches per hash slot are tested.
    pub log_bucket: u32,
    /// Log2 of hash table size (`args[5]`).
    pub log_ht_size: u32,
}

/// Run the configured preprocessing transform on `input` and return
/// the byte stream that the matching PCOMP postprocessor will turn
/// back into `input`. For level 3 (BWT) the trailing 4 bytes encode
/// the BWT index.
pub fn preprocess(input: &[u8], args: LzArgs) -> Vec<u8> {
    let level = args.level_flag & 3;
    debug_assert!((1..=3).contains(&level));

    // Optional E8E9 prefilter — done in place on a copy so we don't
    // poison the caller's slice.
    let mut buf: Vec<u8> = input.to_vec();
    if (args.level_flag & 4) != 0 {
        crate::preproc::e8e9_forward(&mut buf);
    }

    match level {
        2 => preprocess_lz77_byte(&buf, args),
        3 => preprocess_bwt(&buf),
        _ => panic!("level 1 (variable-bit LZ77) not yet ported"),
    }
}

// -------------------- Level 3: BWT -----------------------------------

fn preprocess_bwt(input: &[u8]) -> Vec<u8> {
    let n = input.len();
    let mut out = Vec::with_capacity(n + 5);
    if n == 0 {
        // Upstream emits 0xFF then four zero index bytes.
        out.push(0xFF);
        out.extend_from_slice(&[0u8; 4]);
        return out;
    }

    // SA[0..n] over the byte alphabet, libsais convention.
    let sa = bsc_rs::sais::sais_u8(input);

    // First emitted byte: `in[n-1]` (the cyclic-wrap character).
    out.push(input[n - 1]);

    let mut idx: u32 = 0;
    for i in 1..=n {
        let s = sa[i - 1];
        if s == 0 {
            // Position 0 in SA marks the "sentinel" row. Upstream
            // emits 0xFF here and records the BWT index.
            idx = i as u32;
            out.push(0xFF);
        } else {
            out.push(input[s - 1]);
        }
    }

    // 4 bytes of `idx` little-endian.
    out.push((idx & 0xFF) as u8);
    out.push(((idx >> 8) & 0xFF) as u8);
    out.push(((idx >> 16) & 0xFF) as u8);
    out.push(((idx >> 24) & 0xFF) as u8);
    out
}

// -------------------- Level 2: byte-aligned LZ77 ----------------------

fn preprocess_lz77_byte(input: &[u8], args: LzArgs) -> Vec<u8> {
    let n = input.len();
    let min_match = args.min_match.max(1) as usize;
    let max_match = (1 << 14) * 3; // matches upstream `BUFSIZE * 3`
    let max_literal = (1 << 14) / 4;
    let bucket = ((1u32 << args.log_bucket) - 1) as usize;
    let ht_bits = args.log_ht_size.max(8) as usize;
    let ht_size = 1usize << ht_bits;
    let ht_mask = ht_size - 1;
    let check_bits = 12 - args.log_block_mib as i32;
    let check_bits = check_bits.max(0) as u32;
    let check_mask: u32 = (1u32 << check_bits) - 1;
    let shift1 = if min_match > 0 { (ht_bits as u32 - 1) / min_match as u32 + 1 } else { 1 };

    let mut ht: Vec<u32> = vec![0; ht_size];
    let mut out = Vec::with_capacity(n + n / 16 + 32);

    let mut i: usize = 0;
    let mut lit_start: Option<usize> = None;

    fn emit_literal(out: &mut Vec<u8>, input: &[u8], lit_start: &mut Option<usize>, end: usize) {
        if let Some(start) = *lit_start {
            let mut j = start;
            while j < end {
                let take = (end - j).min(64);
                // 00xxxxxx — `take - 1` literals follow.
                out.push((take - 1) as u8);
                out.extend_from_slice(&input[j..j + take]);
                j += take;
            }
            *lit_start = None;
        }
    }

    fn emit_match(out: &mut Vec<u8>, mut len: usize, off: usize, min_match: usize) {
        // Split into runs ≤ min_match + 63 so the length fits the
        // 6-bit field. Match codes in upstream:
        //   01xxxxxx [off_hi off_lo]                  (off < 1<<16)
        //   10xxxxxx [off_hi off_mid off_lo]          (off < 1<<24)
        //   11xxxxxx [off_hi off_a off_b off_lo]      (off ≤ 1<<32)
        let off = off - 1; // upstream stores off-1
        while len > 0 {
            let len1 = if len > min_match * 2 + 63 {
                min_match + 63
            } else if len > min_match + 63 {
                len - min_match
            } else {
                len
            };
            let lcode = (len1 - min_match) as u8;
            if off < (1 << 16) {
                out.push(0x40 | lcode);
                out.push((off >> 8) as u8);
                out.push((off & 0xFF) as u8);
            } else if off < (1 << 24) {
                out.push(0x80 | lcode);
                out.push((off >> 16) as u8);
                out.push((off >> 8) as u8);
                out.push((off & 0xFF) as u8);
            } else {
                out.push(0xC0 | lcode);
                out.push((off >> 24) as u8);
                out.push((off >> 16) as u8);
                out.push((off >> 8) as u8);
                out.push((off & 0xFF) as u8);
            }
            len -= len1;
        }
    }

    let mut h1: u32 = 0;

    while i < n {
        let mut best_len = 0usize;
        let mut best_p = 0usize;

        if i + min_match + 4 <= n {
            // Try a few hash buckets for the longest match.
            for k in 0..=bucket {
                let slot = (h1 ^ (k as u32)) & (ht_size as u32 - 1);
                let entry = ht[slot as usize];
                if entry == 0 { continue; }
                if (entry & check_mask) != ((input[i + 3] as u32) & check_mask) { continue; }
                let p = (entry >> check_bits) as usize;
                if p >= i { continue; }
                if p + best_len >= n || i + best_len >= n { continue; }
                if input[p + best_len] != input[i + best_len] { continue; }
                // Extend the match.
                let mut l = 0usize;
                while i + l < n && l < max_match && input[p + l] == input[i + l] {
                    l += 1;
                }
                if l > best_len {
                    best_len = l;
                    best_p = p;
                }
                if best_len >= 128 { break; }
            }
        }

        let off = if best_len >= min_match { i.saturating_sub(best_p) } else { 0 };
        let take_match = best_len >= min_match
            && off > 0
            && best_len >= min_match + (off >= (1 << 16)) as usize + (off >= (1 << 24)) as usize;

        if take_match {
            // Flush pending literals first.
            emit_literal(&mut out, input, &mut lit_start, i);
            emit_match(&mut out, best_len, off, min_match);

            // Update hash table for the matched region. We update
            // every position so future matches can land anywhere.
            for step in 0..best_len {
                let pos = i + step;
                if pos + 4 <= n {
                    let entry = ((pos as u32) << check_bits) | ((input[pos + 3] as u32) & check_mask);
                    let slot = ((pos as u32 * 1234547) >> 19) & (bucket as u32);
                    let h_slot = h1 ^ slot;
                    ht[(h_slot & (ht_size as u32 - 1)) as usize] = entry;
                    if pos + min_match < n {
                        h1 = (((h1.wrapping_mul(5)) << shift1)
                              .wrapping_add((input[pos + min_match] as u32 + 1).wrapping_mul(123456791)))
                            & (ht_size as u32 - 1);
                    }
                }
            }
            i += best_len;
        } else {
            // Literal byte.
            if lit_start.is_none() { lit_start = Some(i); }
            // Update hash for this position.
            if i + 4 <= n {
                let entry = ((i as u32) << check_bits) | ((input[i + 3] as u32) & check_mask);
                let slot = ((i as u32 * 1234547) >> 19) & (bucket as u32);
                let h_slot = h1 ^ slot;
                ht[(h_slot & (ht_size as u32 - 1)) as usize] = entry;
                if i + min_match < n {
                    h1 = (((h1.wrapping_mul(5)) << shift1)
                          .wrapping_add((input[i + min_match] as u32 + 1).wrapping_mul(123456791)))
                        & (ht_size as u32 - 1);
                }
            }
            i += 1;
            if let Some(start) = lit_start {
                if i - start >= max_literal {
                    emit_literal(&mut out, input, &mut lit_start, i);
                }
            }
        }
        // Avoid borrowck: `lit_start` is checked above; we can't use
        // `&mut` to call emit_literal without ending the borrow.
        let _ = ht_mask;
    }

    // Flush trailing literals.
    emit_literal(&mut out, input, &mut lit_start, n);
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The level-3 BWT output is structurally `in[n-1] | bwt | idx_LE`
    /// with length `n + 5`. Verify the framing bytes for a tiny input.
    #[test]
    fn bwt_framing_basic() {
        let out = preprocess(b"banana", LzArgs {
            log_block_mib: 0, level_flag: 3,
            min_match: 0, min_match2: 0, log_bucket: 0, log_ht_size: 0,
        });
        assert_eq!(out.len(), 6 + 5);
        assert_eq!(out[0], b'a');
    }

    /// Empty input: BWT emits the canonical `[0xFF, 0,0,0,0]` frame.
    #[test]
    fn bwt_empty() {
        let out = preprocess(b"", LzArgs {
            log_block_mib: 0, level_flag: 3,
            min_match: 0, min_match2: 0, log_bucket: 0, log_ht_size: 0,
        });
        assert_eq!(out, vec![0xFF, 0, 0, 0, 0]);
    }

    /// Level-2 LZ77 bytes are a literal-only stream when the input
    /// has no repeats — every byte becomes part of a 64-byte literal
    /// run. Validate we don't emit any match codes here.
    #[test]
    fn lz77_no_matches_emits_only_literals() {
        let inp: Vec<u8> = (0..200u8).collect();
        let out = preprocess(&inp, LzArgs {
            log_block_mib: 0, level_flag: 2,
            min_match: 4, min_match2: 0, log_bucket: 4, log_ht_size: 16,
        });
        // Each literal block: 1 byte length + N bytes data, N≤64.
        // 200 literals chunked into runs: 64,64,64,8 → 4 blocks =
        // 4 length bytes + 200 data bytes.
        assert_eq!(out.len(), 200 + 4);
        // Literal length codes are < 0x40 (top 2 bits 00).
        for code in [out[0], out[65], out[130], out[195]] {
            assert!(code < 0x40, "expected literal code, got 0x{:02x}", code);
        }
    }
}
